# Version format
version: 1.0.{build}

# Build worker image
image: Visual Studio 2019

# Build Configuration
configuration: Debug

install:
  - set QTDIR=D:\Qt\5.14.2\5.14.2\msvc2017

# MSBuild settings
build:
  project: Team00\Code00\StartupSPASolution.sln
  verbosity: quiet

# Omitted the tests, as they are not relevant for the question