# Version format
version: 1.0.{build}

# Build worker image
image: Visual Studio 2019

install:
  - set QTDIR=C:\Qt\5.14.2\msvc2017
  - echo $QTDIR$
  - set PATH=%PATH%;%QTDIR%\bin;

build_script:
  - MSBuild.exe Team00\Code00\StartupSPASolution.sln /p:Configuration=Debug /p:Platform="Win32"

# Omitted the tests, as they are not relevant for the question
      
test_script:
  - echo Running UnitTesting
  - vstest.console /logger:Appveyor Team00\Code00\Debug\UnitTesting.dll
  - vstest.console /logger:Appveyor Team00\Code00\Debug\IntegrationTesting.dll
